# Generated by Django 5.1.3 on 2025-06-15 16:07

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hub', '0003_festivalticket_workshopregistration_handcraft_price_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Artwork',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('description', models.TextField()),
            ],
        ),
        migrations.RemoveField(
            model_name='comment',
            name='painting',
        ),
        migrations.AddField(
            model_name='comment',
            name='artwork',
            field=models.ForeignKey(default=5, on_delete=django.db.models.deletion.CASCADE, related_name='comments', to='hub.artwork'),
            preserve_default=False,
        ),
        migrations.CreateModel(
            name='HandcraftComment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('handcraft', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='comments', to='hub.handcraft')),
            ],
        ),
    ]
