# Generated by Django 5.1.3 on 2025-06-15 16:19

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hub', '0004_artwork_remove_comment_painting_comment_artwork_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comment',
            name='artwork',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='hub.artwork'),
        ),
    ]
