# Generated by Django 5.1.3 on 2025-06-16 03:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('hub', '0006_profile_delete_comment'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Artwork',
        ),
    ]
