# Generated by Django 5.1.3 on 2025-06-16 03:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hub', '0007_delete_artwork'),
    ]

    operations = [
        migrations.CreateModel(
            name='Artwork',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('description', models.TextField()),
            ],
        ),
    ]
