# Generated by Django 5.1.3 on 2025-06-16 03:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hub', '0008_artwork'),
    ]

    operations = [
        migrations.AddField(
            model_name='artwork',
            name='artist',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='artwork',
            name='category',
            field=models.CharField(choices=[('abstract', 'Abstract'), ('painting', 'Painting')], default='painting', max_length=20),
        ),
        migrations.AddField(
            model_name='artwork',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='artworks/'),
        ),
    ]
