# Generated by Django 5.1.3 on 2025-06-16 03:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('hub', '0009_artwork_artist_artwork_category_artwork_image'),
    ]

    operations = [
        migrations.DeleteModel(
            name='UserProfile',
        ),
    ]
